name: Increment Version

on:
  push:
    branches:
      - master

jobs:
  increment-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Get current version
        id: get-version
        run: echo "current_version=$(cat version.txt)" >> $GITHUB_OUTPUT

      - name: Determine version increment
        id: determine-increment
        run: |
          # Parse the latest commit message and determine the type of change
          COMMIT_MESSAGE=$(git log --format=%B -n 1 HEAD)
          if [[ "$COMMIT_MESSAGE" == "fix:"* ]]; then
            echo "increment=patch" >> $GITHUB_OUTPUT
          elif [[ "$COMMIT_MESSAGE" == "feat:"* ]]; then
            echo "increment=minor" >> $GITHUB_OUTPUT
          elif [[ "$COMMIT_MESSAGE" == "fix!"* ]] || [[ "$COMMIT_MESSAGE" == "feat!"* ]]; then
            echo "increment=major" >> $GITHUB_OUTPUT
          else
            echo "increment=none" >> $GITHUB_OUTPUT
          fi
      - name: test Workflow
        run: |
          echo ${{ steps.determine-increment.outputs.increment}} ~~
      # - name: Increment version
      #   id: increment-version
      #   run: |
      #     # Parse the current version using semver
      #     IFS='.' read -r major minor patch <<< "$(cat version.txt)"
          
      #     # Determine the type of increment and update the version number accordingly
      #     INCREMENT_TYPE=${{ steps.determine-increment.outputs.increment }}
      #     if [[ "$INCREMENT_TYPE" == "patch" ]]; then
      #       patch=$((patch + 1))
      #     elif [[ "$INCREMENT_TYPE" == "minor" ]]; then
      #       minor=$((minor + 1))
      #       patch=0
      #     elif [[ "$INCREMENT_TYPE" == "major" ]]; then
      #       major=$((major + 1))
      #       minor=0
      #       patch=0
      #     fi

      #     # Update the version file
      #     echo "$major.$minor.$patch" > version.txt

      # - name: Commit version changes
      #   run: |
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"
      #     git add version.txt
      #     git commit -m "Bump version to $(cat version.txt)"
      
      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: ${{ github.ref }}
