on:
  push:
    branches:
      - master
name: build-and-release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install pyinstaller
      # - name: Build application
      #   run: |
      #     pyinstaller api/ws_serve.py
      #     pyinstaller --add-data ui:ui ui/serve.py
      # - name: Package application
      #   run: tar -czf app.tgz dist/ws_serve dist/serve
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: myapp
          path: |
            api
            ui
  # release:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create release
        id: create-new-release
        uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.TOKEN }}
          release-type: simple
          package-name: tesssstname
          # extra-files: |
          #   myapp
        if: ${{ steps.create-new-release.outputs.release_created }}
      - name: test step
        run: |
          echo ${{ steps.create-new-release.outputs.tag_name }}
          echo "^^~~^^"
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: build.sh
          # asset_name: myapp-${{ steps.create-new-release.outputs.tag_name }}.zip
