name: Buld a release

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get version
        id: get-version
        run: |
          echo "tag=v$(cat version.txt)" >> $GITHUB_OUTPUT
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install pyinstaller websockets
      - name: Build application
        run: |
          pyinstaller api/ws_serve.py
          pyinstaller --add-data ui:ui ui/serve.py
      - name: Package application
        id: package-app
        run: |
          zipname=$(basename ${GITHUB_REPOSITORY})-Ubuntu-${{ steps.get-version.outputs.tag }}.zip
          cd dist && zip -r $zipname ws_serve/ serve/ 
          fullpath=$(realpath $zipname)
          cd .. 
          zip -u dist/$zipname start.sh
          echo "dist_path=$fullpath" >> $GITHUB_OUTPUT
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get-version.outputs.tag }}
          files: |
            ${{ steps.package-app.outputs.dist_path }}
