on:
  push:
    branches:
      - master
name: build-and-release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install pyinstaller
      # - name: Build application
      #   run: |
      #     pyinstaller api/ws_serve.py
      #     pyinstaller --add-data ui:ui ui/serve.py
      - name: Package application
        run: tar -czf app.tgz api/ ui/
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: myapp
          path: app.tgz
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install @semantic-release/github -D

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --branches master
